bandpowers:
  lsplit: 52
  nb_log: 28
  nlb: 20
  nlb_lin: 10
  type: linlog
data_vectors:
- covar_type: comb_m
  name: wisc1
  twopoints:
  - lmin: 10
    tracers:
    - wisc1
    - wisc1
  - lmin: 0
    tracers:
    - wisc1
    - y_milca
  type: Cl
global:
  n_iter: 3
  nside: 2048
  output_dir: /mnt/extraspace/nikfilippas/yxgxk/output_default
jk:
  do: true
  nside: 8
  store_mcm: true
maps:
- beam: false
  dndz: data/dndz/WISC_bin1.txt
  map: data/maps/2dstarsub_WISC_cleaned_public.bin_0.1_z_0.15.Pix512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.44851399116254714
    alpha: 1.0
    b_hydro: 0.13445529991375527
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 10.566915700652395
    lM1: 11.856040531728171
    lMmin: 10.566915700652395
    n_s: 0.9665
    r_corr_gk: 0.15391042875162592
    r_corr_gy: -0.6191623216370346
    sigma8: 0.8001868841125964
    sigmaLogM: 0.15
    width: 0.845672610496452
  name: wisc1
  ns_independent: false
  systematics:
  - scos_plates
  - Star_contamination/2dstarcorr_WISC_cleaned_public.bin_0.1_z_0.15.Pix512.fits
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: 10.0
  map: data/maps/milca_ymaps.fits
  mask: mask_tsz
  name: y_milca
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: y
- beam: 10.0
  map: data/maps/nilc_ymaps.fits
  mask: mask_tsz
  name: y_nilc
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: y
- beam: 10.0
  map: data/maps/HFI_SkyMap_545_2048_R2.02_full.fits
  mask: mask_545
  name: dust_545
  type: d
- beam: false
  map: data/maps/COM_CompMap_Lensing_2048_R2.00_map.fits
  mask: mask_lens_2015
  name: lens
  ns_independent: false
  systematics: None
  type: k
masks:
  mask_545: data/maps/mask_planck20.fits
  mask_lens_2015: data/maps/COM_CompMap_Lensing_2048_R2.00_mask.fits
  mask_lowz: data/maps/mask_v3.fits
  mask_tsz: data/maps/mask_planck60.fits
mcmc:
  continue_mcmc: true
  debug: false
  hbias: tinker10
  kmax: 1.0
  mfunc: tinker08
  n_steps: 1000
  n_walkers: 96
  run_name: lensing_gy
  save_par: false
params:
- alias: lMmin
  label: M_0
  name: lM0
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 12.5
  vary: false
- label: M_1
  name: lM1
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 13.5
  vary: true
- label: M_{\rm min}
  name: lMmin
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 12.0
  vary: true
- label: f_c
  name: fc
  prior:
    type: TopHat
    values:
    - 0.0
    - 1.0
  value: 1.0
  vary: false
- label: \alpha
  name: alpha
  prior:
    type: TopHat
    values:
    - 0.0
    - 3.0
  value: 1.0
  vary: false
- alias: beta_gal
  label: \beta_{\rm max}
  name: beta_max
- label: beta_g
  name: beta_gal
  prior:
    type: TopHat
    values:
    - 0.1
    - 10.0
  value: 1.0
  vary: false
- label: \sigma_{{\rm ln}M}
  name: sigmaLogM
  prior:
    type: TopHat
    values:
    - 0.01
    - 1.0
  value: 0.15
  vary: false
- label: b_H
  name: b_hydro
  prior:
    type: TopHat
    values:
    - 0.0
    - 1.0
  value: 0.3
  vary: true
- label: \rho_{gy}
  name: r_corr_gy
  prior:
    type: TopHat
    values:
    - -1.0
    - 1.0
  value: 0.0
  vary: true
- label: \rho_{g\kappa}
  name: r_corr_gk
  prior:
    type: TopHat
    values:
    - -0.5
    - 0.5
  value: 0.0
  vary: true
- label: w_{N(z)}
  name: width
  prior:
    type: TopHat
    values:
    - 0.8
    - 1.2
  value: 1.0
  vary: true
- label: \Omega_c
  name: Omega_c
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.26066676
  vary: false
- label: \Omega_b
  name: Omega_b
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.048974682
  vary: false
- label: h
  name: h
  prior:
    type: TopHat
    values:
    - 0.55
    - 0.8
  value: 0.6766
  vary: false
- label: \sigma_8
  name: sigma8
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.8102
  vary: true
- label: n_s
  name: n_s
  prior:
    type: TopHat
    values:
    - 0.8
    - 1.2
  value: 0.9665
  vary: false
- label: \a_\textrm{HMcorr}
  name: a_HMcorr
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.5
  value: 0.36
  vary: true
