bandpowers:
  lsplit: 52
  nb_log: 28
  nlb: 20
  nlb_lin: 10
  type: linlog
data_vectors:
- covar_type: comb_m
  name: 2mpz
  twopoints:
  - lmin: 0
    tracers:
    - 2mpz
    - 2mpz
  - lmin: 0
    tracers:
    - 2mpz
    - y_milca
  type: Cl
global:
  n_iter: 3
  nside: 2048
  output_dir: /mnt/extraspace/nikfilippas/yxgxk/output_default
jk:
  do: true
  nside: 8
  store_mcm: true
maps:
- beam: false
  dndz: data/dndz/2MPZ_bin1.txt
  map: data/maps/2mpz_05_01_512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.0486
    Omega_c: 0.2589
    h: 0.6774
    n_s: 0.9667
    sigma8: 0.8159
    b_hydro: 0.33652023
    lM1: 12.99472018
    lMmin: 11.66317664
    r_corr_gy: -0.10361521
    a_HMcorr: 0.315
    width: 1.19939348
    alpha: 1.0
    fc: 1.0
    sigmaLogM: 0.15
  name: 2mpz
  ns_independent: false
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: 10.0
  map: data/maps/milca_ymaps.fits
  mask: mask_tsz
  name: y_milca
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: y
- beam: 10.0
  map: data/maps/HFI_SkyMap_545_2048_R2.02_full.fits
  mask: mask_545
  name: dust_545
  type: d
masks:
  mask_545: data/maps/mask_planck20.fits
  mask_lowz: data/maps/mask_v3.fits
  mask_tsz: data/maps/mask_planck60.fits
mcmc:
  continue_mcmc: true
  debug: false
  hbias: tinker10
  kmax: 1.0
  mfunc: tinker08
  n_steps: 0
  n_walkers: 96
  run_name: lensing_gy
params:
- alias: lMmin
  label: M_0
  name: lM0
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 11.66317664
  vary: false
- label: M_1
  name: lM1
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 12.99472018
  vary: true
- label: M_{\rm min}
  name: lMmin
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 11.66317664
  vary: true
- label: f_c
  name: fc
  prior:
    type: TopHat
    values:
    - 0.0
    - 1.0
  value: 1.0
  vary: false
- label: \alpha
  name: alpha
  prior:
    type: TopHat
    values:
    - 0.0
    - 3.0
  value: 1.0
  vary: false
- label: \sigma_{{\rm ln}M}
  name: sigmaLogM
  prior:
    type: TopHat
    values:
    - 0.01
    - 1.0
  value: 0.15
  vary: false
- label: b_H
  name: b_hydro
  prior:
    type: TopHat
    values:
    - 0.0
    - 1.0
  value: 0.33652023
  vary: true
- label: \rho_{gy}
  name: r_corr_gy
  prior:
    type: TopHat
    values:
    - -1.0
    - 1.0
  value: -0.10361521
  vary: true
- label: w_{N(z)}
  name: width
  prior:
    type: TopHat
    values:
    - 0.8
    - 1.2
  value: 1.19939348
  vary: true
- label: \Omega_c
  name: Omega_c
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.2589
  vary: false
- label: \Omega_b
  name: Omega_b
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.0486
  vary: false
- label: h
  name: h
  prior:
    type: TopHat
    values:
    - 0.55
    - 0.8
  value: 0.6774
  vary: false
- label: \sigma_8
  name: sigma8
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.8159
  vary: true
- label: n_s
  name: n_s
  prior:
    type: TopHat
    values:
    - 0.8
    - 1.2
  value: 0.9667
  vary: false
- label: a_{\rm HMcorr}
  name: a_HMcorr
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.5
  value: 0.315
  vary: true
