bandpowers:
  lsplit: 52
  nb_log: 28
  nlb: 20
  nlb_lin: 10
  type: linlog
data_vectors:
- covar_type: comb_m
  name: wisc5
  twopoints:
  - lmin: 10
    tracers:
    - wisc5
    - wisc5
  - lmin: 0
    tracers:
    - wisc5
    - y_milca
  type: Cl
global:
  n_iter: 3
  nside: 2048
  output_dir: /mnt/extraspace/nikfilippas/yxgxk/output_lensing
jk:
  do: true
  nside: 8
  store_mcm: true
maps:
- beam: false
  dndz: data/dndz/2MPZ_bin1.txt
  map: data/maps/2mpz_05_01_512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.4869430841809267
    alpha: 1.0
    b_hydro: 0.3596746053023261
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 10.088453969327944
    lM1: 11.46262381785892
    lMmin: 10.088453969327944
    n_s: 0.9665
    r_corr_gk: 0.26131795443425043
    r_corr_gy: -0.5166380809397779
    sigma8: 0.9125089003720152
    sigmaLogM: 0.15
    width: 1.199999999993615
  name: 2mpz
  ns_independent: false
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: false
  dndz: data/dndz/WISC_bin1.txt
  map: data/maps/2dstarsub_WISC_cleaned_public.bin_0.1_z_0.15.Pix512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.44891594696065296
    alpha: 1.0
    b_hydro: 0.1357438158962617
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 10.566933238812311
    lM1: 11.855575218548077
    lMmin: 10.566933238812311
    n_s: 0.9665
    r_corr_gk: 0.15391042872814525
    r_corr_gy: -0.6193060330569599
    sigma8: 0.7998995049470106
    sigmaLogM: 0.15
    width: 0.8460796385376906
  name: wisc1
  ns_independent: false
  systematics:
  - scos_plates
  - Star_contamination/2dstarcorr_WISC_cleaned_public.bin_0.1_z_0.15.Pix512.fits
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: false
  dndz: data/dndz/WISC_bin2.txt
  map: data/maps/2dstarsub_WISC_cleaned_public.bin_0.15_z_0.2.Pix512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.4191400329037954
    alpha: 1.0
    b_hydro: 0.18801025835054094
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 10.549661222543671
    lM1: 11.794200755238226
    lMmin: 10.549661222543671
    n_s: 0.9665
    r_corr_gk: 0.1639599722004509
    r_corr_gy: -0.5964981476184282
    sigma8: 0.8135131715476474
    sigmaLogM: 0.15
    width: 0.8484812190499794
  name: wisc2
  ns_independent: false
  systematics:
  - scos_plates
  - Star_contamination/2dstarcorr_WISC_cleaned_public.bin_0.15_z_0.2.Pix512.fits
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: false
  dndz: data/dndz/WISC_bin3.txt
  map: data/maps/2dstarsub_WISC_cleaned_public.bin_0.2_z_0.25.Pix512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.4304997179776786
    alpha: 1.0
    b_hydro: 0.2476317226692265
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 11.287051421533828
    lM1: 12.492135977304324
    lMmin: 11.287051421533828
    n_s: 0.9665
    r_corr_gk: 0.3173420606435626
    r_corr_gy: -0.6180678188777896
    sigma8: 0.8262939050529468
    sigmaLogM: 0.15
    width: 1.0066382202382174
  name: wisc3
  ns_independent: false
  systematics:
  - scos_plates
  - Star_contamination/2dstarcorr_WISC_cleaned_public.bin_0.2_z_0.25.Pix512.fits
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: false
  dndz: data/dndz/WISC_bin4.txt
  map: data/maps/2dstarsub_WISC_cleaned_public.bin_0.25_z_0.3.Pix512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.48033660847785303
    alpha: 1.0
    b_hydro: 0.004266339934359555
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 12.0017556649036
    lM1: 13.140135286773353
    lMmin: 12.0017556649036
    n_s: 0.9665
    r_corr_gk: 0.0842495989334907
    r_corr_gy: -0.5412754039894383
    sigma8: 0.7172490663209614
    sigmaLogM: 0.15
    width: 1.1645910249571385
  name: wisc4
  ns_independent: false
  systematics:
  - scos_plates
  - Star_contamination/2dstarcorr_WISC_cleaned_public.bin_0.25_z_0.3.Pix512.fits
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: false
  dndz: data/dndz/WISC_bin5.txt
  map: data/maps/2dstarsub_WISC_cleaned_public.bin_0.3_z_0.35.Pix512.fits
  mask: mask_lowz
  model:
    Omega_b: 0.048974682
    Omega_c: 0.26066676
    a_HMcorr: 0.10000000000003045
    alpha: 1.0
    b_hydro: 0.17791604786210855
    beta_gal: 1.0
    beta_max: 1.0
    fc: 1.0
    h: 0.6766
    lM0: 12.409079049583832
    lM1: 13.078173845834668
    lMmin: 12.409079049583832
    n_s: 0.9665
    r_corr_gk: 0.26131794997572383
    r_corr_gy: -0.642227317746194
    sigma8: 0.7738308593004929
    sigmaLogM: 0.15
    width: 1.1999999999999365
  name: wisc5
  ns_independent: false
  systematics:
  - scos_plates
  - Star_contamination/2dstarcorr_WISC_cleaned_public.bin_0.3_z_0.35.Pix512.fits
  - data/maps/lambda_sfd_ebv.fits
  type: g
- beam: 10.0
  map: data/maps/milca_ymaps.fits
  mask: mask_tsz
  name: y_milca
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: y
- beam: 10.0
  map: data/maps/nilc_ymaps.fits
  mask: mask_tsz
  name: y_nilc
  systematics:
  - data/maps/lambda_sfd_ebv.fits
  type: y
- beam: 10.0
  map: data/maps/HFI_SkyMap_545_2048_R2.02_full.fits
  mask: mask_545
  name: dust_545
  type: d
- beam: false
  map: data/maps/COM_CompMap_Lensing_2048_R2.00_map.fits
  mask: mask_lens_2015
  name: lens
  ns_independent: false
  systematics: None
  type: k
masks:
  mask_545: data/maps/mask_planck20.fits
  mask_lens_2015: data/maps/COM_CompMap_Lensing_2048_R2.00_mask.fits
  mask_lowz: data/maps/mask_v3.fits
  mask_tsz: data/maps/mask_planck60.fits
mcmc:
  continue_mcmc: true
  debug: false
  hbias: tinker10
  kmax: 1.0
  mfunc: tinker08
  n_steps: 10000
  n_walkers: 96
  run_name: lensing_gy
params:
- alias: lMmin
  label: M_0
  name: lM0
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 12.0
  vary: false
- label: M_1
  name: lM1
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 13.0
  vary: true
- label: M_{\rm min}
  name: lMmin
  prior:
    type: TopHat
    values:
    - 10.0
    - 16.0
  value: 12.0
  vary: true
- label: f_c
  name: fc
  prior:
    type: TopHat
    values:
    - 0.0
    - 1.0
  value: 1.0
  vary: false
- label: \alpha
  name: alpha
  prior:
    type: TopHat
    values:
    - 0.0
    - 3.0
  value: 1.0
  vary: false
- alias: beta_gal
  label: \beta_{\rm max}
  name: beta_max
- label: beta_g
  name: beta_gal
  prior:
    type: TopHat
    values:
    - 0.1
    - 10.0
  value: 1.0
  vary: false
- label: \sigma_{{\rm ln}M}
  name: sigmaLogM
  prior:
    type: TopHat
    values:
    - 0.01
    - 1.0
  value: 0.15
  vary: false
- label: b_H
  name: b_hydro
  prior:
    type: TopHat
    values:
    - 0.0
    - 1.0
  value: 0.25
  vary: true
- label: \rho_{gy}
  name: r_corr_gy
  prior:
    type: TopHat
    values:
    - -1.0
    - 1.0
  value: 0.0
  vary: true
- label: \rho_{g\kappa}
  name: r_corr_gk
  prior:
    type: TopHat
    values:
    - -0.5
    - 0.5
  value: 0.0
  vary: true
- label: w_{N(z)}
  name: width
  prior:
    type: TopHat
    values:
    - 0.8
    - 1.2
  value: 1.0
  vary: true
- label: \Omega_c
  name: Omega_c
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.26066676
  vary: false
- label: \Omega_b
  name: Omega_b
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.9
  value: 0.048974682
  vary: false
- label: h
  name: h
  prior:
    type: TopHat
    values:
    - 0.55
    - 0.8
  value: 0.6766
  vary: false
- label: \sigma_8
  name: sigma8
  prior:
    type: TopHat
    values:
    - 0.5
    - 0.95
  value: 0.8102
  vary: true
- label: n_s
  name: n_s
  prior:
    type: TopHat
    values:
    - 0.8
    - 1.2
  value: 0.9665
  vary: false
- label: a_{\rm HMcorr}
  name: a_HMcorr
  prior:
    type: TopHat
    values:
    - 0.1
    - 0.5
  value: 0.36
  vary: true
